name: Deploy Page React Hello World

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npm test

      - name: Construir aplicação
        run: |
          npm run build
          mv build docs
          touch docs/.nojekyll  # Desativa o Jekyll para evitar erro no GitHub Pages

      - name: Verificar conteúdo da pasta docs
        run: ls -l docs

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "Release v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Fazer Deploy no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

  notify_failure:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    needs: [build, deploy]
    steps:
      - name: Enviar e-mail em caso de falha
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚨 CI/CD Falhou no Repositório ${{ github.repository }}"
          body: |
            O pipeline falhou na etapa: ${{ github.job }}
            Commit: ${{ github.sha }}
            Autor: ${{ github.actor }}
            Veja mais detalhes: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: ${{ secrets.EMAIL_DEV }}
          from: notifications@github.com
